/* SPDX-FileCopyrightText: (C) 2023-2025 ilmmatias
 * SPDX-License-Identifier: GPL-3.0-or-later */

#ifndef _ACPI_DETAIL_ACPIDEFS_H_
#define _ACPI_DETAIL_ACPIDEFS_H_

#define ACPI_REVISION 0x0000000000000000

#define ACPI_EMPTY 0
#define ACPI_INTEGER 1
#define ACPI_STRING 2
#define ACPI_BUFFER 3
#define ACPI_PACKAGE 4
#define ACPI_FIELD_UNIT 5
#define ACPI_DEVICE 6
#define ACPI_EVENT 7
#define ACPI_METHOD 8
#define ACPI_MUTEX 9
#define ACPI_REGION 10
#define ACPI_POWER 11
#define ACPI_PROCESSOR 12
#define ACPI_THERMAL 13
#define ACPI_BUFFER_FIELD 14
#define ACPI_DEBUG 16
#define ACPI_ALIAS 17
#define ACPI_SCOPE 18
#define ACPI_REFERENCE 19
#define ACPI_INDEX 20
#define ACPI_LOCAL 21
#define ACPI_ARG 22

#define ACPI_FIELD 0
#define ACPI_BANK_FIELD 1
#define ACPI_INDEX_FIELD 2

#define ACPI_SPACE_SYSTEM_MEMORY 0
#define ACPI_SPACE_SYSTEM_IO 1
#define ACPI_SPACE_PCI_CONFIG 2
#define ACPI_SPACE_EMBEDDED_CONTROL 3
#define ACPI_SPACE_SMBUS 4
#define ACPI_SPACE_SYSTEM_CMOS 5
#define ACPI_SPACE_PCI_BAR_TARGET 6
#define ACPI_SPACE_IPMI 7
#define ACPI_SPACE_GENERAL_PURPOSE_IO 8
#define ACPI_SPACE_GENERIC_SERIAL_BUS 9
#define ACPI_SPACE_PCC 10

#endif /* _ACPI_DETAIL_ACPIDEFS_H_ */
