/* SPDX-FileCopyrightText: (C) 2025 ilmmatias
 * SPDX-License-Identifier: GPL-3.0-or-later */

/* IWYU pragma: private, include <kernel/kdp.h> */

#ifndef _KERNEL_DETAIL_KDPDEFS_H_
#define _KERNEL_DETAIL_KDPDEFS_H_

#include <kernel/detail/kddefs.h>

/* clang-format off */
#if __has_include(ARCH_MAKE_INCLUDE_PATH(kernel/detail, kdpdefs.h))
#include ARCH_MAKE_INCLUDE_PATH(kernel/detail, kdpdefs.h)
#endif /* __has__include */
/* clang-format on */

/* Sync these with the equivalent defines from the WDK matching the wanted source of the KDNET
 * drivers. */

#define KDP_DEVICE_FLAGS_HAL_SCRATCH_ALLOCATED 0x01
#define KDP_DEVICE_FLAGS_BARS_MAPPED 0x02
#define KDP_DEVICE_FLAGS_SCRATCH_ALLOCATED 0x04
#define KDP_DEVICE_FLAGS_UNCACHED_MEMORY 0x08

#define KDP_RESOURCE_NULL 0
#define KDP_RESOURCE_PORT 1
#define KDP_RESOURCE_INTERRUPT 2
#define KDP_RESOURCE_MEMORY 3
#define KDP_RESOURCE_DMA 4
#define KDP_RESOURCE_DEVICE_SPECIFIC 5
#define KDP_RESOURCE_BUS_NUMBER 6
#define KDP_RESOURCE_MEMORY_LARGE 7

#define KDP_NAMESPACE_PCI 0
#define KDP_NAMESPACE_ACPI 1
#define KDP_NAMESPACE_ANY 2
#define KDP_NAMESPACE_NONE 3
#define KDP_NAMESPACE_MA 4

#define KDP_ENVIRONMENT_UNSPECIFIED 0
#define KDP_ENVIRONMENT_BOOT 1
#define KDP_ENVIRONMENT_KERNEL 2
#define KDP_ENVIRONMENT_HYPERVISOR 3
#define KDP_ENVIRONMENT_SK 4
#define KDP_ENVIRONMENT_HCL 5

#define KDP_EXTENSIBILITY_EXPORT_COUNT 15
#define KDP_EXTENSIBILITY_IMPORT_COUNT 33

#define KDP_TRANSMIT_LAST 0x20000000
#define KDP_TRANSMIT_HANDLE 0x40000000
#define KDP_TRANSMIT_ASYNC 0x80000000
#define KDP_HANDLE_FLAGS (KDP_TRANSMIT_LAST | KDP_TRANSMIT_HANDLE | KDP_TRANSMIT_ASYNC)

#define KDP_STATE_EARLY 0
#define KDP_STATE_LATE 1

#define KDP_PROTOCOL_MAGIC "PDKD"
#define KDP_PROTOCOL_MAJOR 1
#define KDP_PROTOCOL_MINOR 0
#define KDP_PROTOCOL_HEADER_SIZE 48
#define KDP_PROTOCOL_MAX_DATAGRAM 1024
#define KDP_PROTOCOL_MAX_PAYLOAD (KDP_PROTOCOL_MAX_DATAGRAM - KDP_PROTOCOL_HEADER_SIZE)

#define KDP_PROTOCOL_FLAG_REQUEST (1u << 0)
#define KDP_PROTOCOL_FLAG_RESPONSE (1u << 1)
#define KDP_PROTOCOL_FLAG_EVENT (1u << 2)
#define KDP_PROTOCOL_FLAG_RETRY (1u << 3)

#define KDP_PROTOCOL_STATUS_SUCCESS 0
#define KDP_PROTOCOL_STATUS_MALFORMED_MESSAGE 1
#define KDP_PROTOCOL_STATUS_UNSUPPORTED_VERSION 2
#define KDP_PROTOCOL_STATUS_INVALID_SESSION 3
#define KDP_PROTOCOL_STATUS_INVALID_SEQUENCE 4
#define KDP_PROTOCOL_STATUS_INVALID_STATE 5
#define KDP_PROTOCOL_STATUS_UNSUPPORTED 6
#define KDP_PROTOCOL_STATUS_INVALID_ARGUMENT 7
#define KDP_PROTOCOL_STATUS_NOT_FOUND 8
#define KDP_PROTOCOL_STATUS_BUSY 9
#define KDP_PROTOCOL_STATUS_ACCESS_VIOLATION 10
#define KDP_PROTOCOL_STATUS_TOO_LARGE 11
#define KDP_PROTOCOL_STATUS_TIMEOUT 12
#define KDP_PROTOCOL_STATUS_CONFLICT 13
#define KDP_PROTOCOL_STATUS_NONRESUMABLE 14
#define KDP_PROTOCOL_STATUS_INTERNAL_ERROR 15

#define KDP_PROTOCOL_HELLO 0x0001
#define KDP_PROTOCOL_PING 0x0002
#define KDP_PROTOCOL_DETACH 0x0003
#define KDP_PROTOCOL_TARGET_OUTPUT 0x0010
#define KDP_PROTOCOL_STOP 0x0011
#define KDP_PROTOCOL_QUERY_STATUS 0x0100
#define KDP_PROTOCOL_LIST_CPUS 0x0101
#define KDP_PROTOCOL_READ_CONTEXT 0x0102
#define KDP_PROTOCOL_READ_PHYSICAL 0x0200
#define KDP_PROTOCOL_READ_VIRTUAL 0x0201
#define KDP_PROTOCOL_READ_PORT 0x0202
#define KDP_PROTOCOL_REQUEST_STOP 0x0300
#define KDP_PROTOCOL_CONTINUE 0x0301
#define KDP_PROTOCOL_SINGLE_STEP 0x0302
#define KDP_PROTOCOL_BREAKPOINT_ADD 0x0400
#define KDP_PROTOCOL_BREAKPOINT_REMOVE 0x0401
#define KDP_PROTOCOL_BREAKPOINT_ENABLE 0x0402
#define KDP_PROTOCOL_BREAKPOINT_DISABLE 0x0403
#define KDP_PROTOCOL_BREAKPOINT_LIST 0x0404

#define KDP_PROTOCOL_CAP_OUTPUT (1ull << 0)
#define KDP_PROTOCOL_CAP_READ_PHYSICAL (1ull << 1)
#define KDP_PROTOCOL_CAP_READ_VIRTUAL (1ull << 2)
#define KDP_PROTOCOL_CAP_READ_PORT (1ull << 3)
#define KDP_PROTOCOL_CAP_STOP (1ull << 4)
#define KDP_PROTOCOL_CAP_CONTEXT (1ull << 5)
#define KDP_PROTOCOL_CAP_CONTINUE (1ull << 6)
#define KDP_PROTOCOL_CAP_STEP (1ull << 7)
#define KDP_PROTOCOL_CAP_SOFTWARE_BREAKPOINT (1ull << 8)
#define KDP_PROTOCOL_CAP_SMP_CONTEXT (1ull << 9)
#define KDP_PROTOCOL_CAP_RECONNECT (1ull << 10)

#define KDP_PROTOCOL_ARCH_AMD64 0x8664
#define KDP_PROTOCOL_CONTEXT_VERSION 1

#define KDP_TARGET_BOOTING 0
#define KDP_TARGET_RUNNING 1
#define KDP_TARGET_STOPPING 2
#define KDP_TARGET_STOPPED 3
#define KDP_TARGET_RESUMING 4
#define KDP_TARGET_PANIC 5

#define KDP_STOP_REASON_MANUAL 0
#define KDP_STOP_REASON_SOFTWARE_BREAKPOINT 1
#define KDP_STOP_REASON_SINGLE_STEP 2
#define KDP_STOP_REASON_DEBUGGER_LOST 3
#define KDP_STOP_REASON_PANIC 4

#define KDP_STOP_FLAG_RESUMABLE (1u << 0)
#define KDP_CONTEXT_VALID_GPR (1ull << 0)
#define KDP_CONTEXT_VALID_INSTRUCTION (1ull << 1)
#define KDP_CONTEXT_VALID_SEGMENTS (1ull << 2)
#define KDP_CONTEXT_VALID_EXCEPTION (1ull << 3)
#define KDP_CONTEXT_VALID_XMM (1ull << 4)

#define KDP_BREAKPOINT_FLAG_ENABLED (1u << 0)
#define KDP_MAX_BREAKPOINTS 64

/* Should this be in here, or somewhere else? */

#define KDP_ANSI_FG_RED "\033[38;5;196m"
#define KDP_ANSI_FG_GREEN "\033[38;5;46m"
#define KDP_ANSI_FG_YELLOW "\033[38;5;226m"
#define KDP_ANSI_FG_BLUE "\033[38;5;51m"

#define KDP_ANSI_RESET "\033[0m"

#endif /* _KERNEL_DETAIL_KDPDEFS_H_ */
