/* SPDX-FileCopyrightText: (C) 2026 ilmmatias
 * SPDX-License-Identifier: GPL-3.0-or-later */

/* IWYU pragma: private, include <kernel/ps.h> */

#ifndef _KERNEL_DETAIL_AMD64_PSTYPES_H_
#define _KERNEL_DETAIL_AMD64_PSTYPES_H_

#define PS_AMD64_THREAD_SIZE 232
#define PS_AMD64_THREAD_OWNED_MUTEX_LIST_OFFSET 56
#define PS_AMD64_THREAD_WAIT_GENERATION_OFFSET 160
#define PS_AMD64_THREAD_WAIT_OBJECT_OFFSET 168
#define PS_AMD64_THREAD_WAIT_COMPLETION_OFFSET 176
#define PS_AMD64_THREAD_PROCESSOR_OFFSET 184
#define PS_AMD64_THREAD_CONTEXT_OFFSET 216

#endif /* _KERNEL_DETAIL_AMD64_PSTYPES_H_ */
