/* SPDX-FileCopyrightText: (C) 2025 ilmmatias
 * SPDX-License-Identifier: GPL-3.0-or-later */

#ifndef _KERNEL_DETAIL_AMD64_HALPDEFS_H_
#define _KERNEL_DETAIL_AMD64_HALPDEFS_H_

#include <kernel/detail/amd64/halptypes.h>
#include <kernel/detail/amd64/kedefs.h>

#define HALP_INT_DISPATCH_IRQL 2
#define HALP_INT_TIMER_IRQL 13
#define HALP_INT_IPI_IRQL 14
#define HALP_INT_SPURIOUS_IRQL 15

#define HALP_INT_DISPATCH_VECTOR 0x21
#define HALP_INT_TIMER_VECTOR 0xD0
#define HALP_INT_IPI_VECTOR 0xE0
#define HALP_INT_SPURIOUS_VECTOR 0xFF

#define HALP_LAPIC_RECORD 0
#define HALP_IOAPIC_RECORD 1
#define HALP_IOAPIC_SOURCE_OVERRIDE_RECORD 2
#define HALP_X2APIC_RECORD 9

#define HALP_PIC_CMD1 0x20
#define HALP_PIC_CMD2 0xA0
#define HALP_PIC_DATA1 0x21
#define HALP_PIC_DATA2 0xA1

#define HALP_PIC_ICW1 0x11
#define HALP_PIC_ICW2_MASTER 0x20
#define HALP_PIC_ICW2_SLAVE 0x28
#define HALP_PIC_ICW3_MASTER 0x04
#define HALP_PIC_ICW3_SLAVE 0x02
#define HALP_PIC_ICW4_MASTER 0x05
#define HALP_PIC_ICW4_SLAVE 0x01
#define HALP_PIC_MASK 0xFF

#define HALP_APIC_MSR 0x1B
#define HALP_APIC_REG_MSR 0x800

#define HALP_APIC_MSR_X2APIC_ENABLE 0x400
#define HALP_APIC_MSR_ENABLE 0x800

#define HALP_APIC_ID_REG 0x20
#define HALP_APIC_VER_REG 0x30
#define HALP_APIC_TPR_REG 0x80
#define HALP_APIC_APR_REG 0x90
#define HALP_APIC_PPR_REG 0xA0
#define HALP_APIC_EOI_REG 0xB0
#define HALP_APIC_RRD_REG 0xC0
#define HALP_APIC_LDR_REG 0xD0
#define HALP_APIC_DFR_REG 0xE0
#define HALP_APIC_SPIV_REG 0xF0
#define HALP_APIC_ISR_REG(n) (0x100 + ((n) << 4))
#define HALP_APIC_TMR_REG(n) (0x180 + ((n) << 4))
#define HALP_APIC_IRR_REG(n) (0x200 + ((n) << 4))
#define HALP_APIC_ESR_REG 0x280
#define HALP_APIC_LVTCMCI_REG 0x2F0
#define HALP_APIC_ICR_REG_LOW 0x300
#define HALP_APIC_ICR_REG_HIGH 0x310
#define HALP_APIC_LVTT_REG 0x320
#define HALP_APIC_LVTTHMR_REG 0x330
#define HALP_APIC_LVTPC_REG 0x340
#define HALP_APIC_LVT0_REG 0x350
#define HALP_APIC_LVT1_REG 0x360
#define HALP_APIC_LVTERR_REG 0x370
#define HALP_APIC_TIMER_ICR_REG 0x380
#define HALP_APIC_TIMER_CCR_REG 0x390
#define HALP_APIC_TIMER_DCR_REG 0x3E0
#define HALP_APIC_SELF_IPI_REG 0x3F0

#define HALP_APIC_ID_VALUE(v) ((v) >> 24)

#define HALP_APIC_VER_MAX_LVT(v) ((((v) >> 16) & 0xFF) + 1)

#define HALP_APIC_ICR_DELIVERY_FIXED 0x00
#define HALP_APIC_ICR_DELIVERY_LOW_PRI 0x01
#define HALP_APIC_ICR_DELIVERY_SMI 0x02
#define HALP_APIC_ICR_DELIVERY_NMI 0x04
#define HALP_APIC_ICR_DELIVERY_INIT 0x05
#define HALP_APIC_ICR_DELIVERY_STARTUP 0x06
#define HALP_APIC_ICR_DELIVERY_INIT_DEASSERT 0x07

#define HALP_APIC_ICR_DESTINATION_MODE_PHYSICAL 0x00
#define HALP_APIC_ICR_DESTINATION_MODE_LOGICAL 0x01

#define HALP_APIC_ICR_LEVEL_DEASSERT 0x00
#define HALP_APIC_ICR_LEVEL_ASSERT 0x01

#define HALP_APIC_ICR_TRIGGER_EDGE 0x00
#define HALP_APIC_ICR_TRIGGER_LEVEL 0x01

#define HALP_APIC_ICR_DESTINATION_TYPE_DEFAULT 0x00
#define HALP_APIC_ICR_DESTINATION_TYPE_SELF 0x01
#define HALP_APIC_ICR_DESTINATION_TYPE_ALL_INCL_SELF 0x02
#define HALP_APIC_ICR_DESTINATION_TYPE_ALL_BUT_SELF 0x03

#define HALP_IOAPIC_INDEX 0x00
#define HALP_IOAPIC_DATA 0x10

#define HALP_IOAPIC_ID_REG 0x00
#define HALP_IOAPIC_VER_REG 0x01
#define HALP_IOAPIC_ARB_REG 0x02
#define HALP_IOAPIC_REDIR_REG_LOW(n) (0x10 + ((n) << 1))
#define HALP_IOAPIC_REDIR_REG_HIGH(n) (0x11 + ((n) << 1))

#define HALP_PML4_LEVEL 0
#define HALP_PML4_BASE ((HalpPageFrame *)0xFFFFFFFFFFFFF000)
#define HALP_PML4_SHIFT 39
#define HALP_PML4_MASK 0x1FF
#define HALP_PML4_SIZE (1ull << HALP_PML4_SHIFT)

#define HALP_PDPT_LEVEL 1
#define HALP_PDPT_BASE ((HalpPageFrame *)0xFFFFFFFFFFE00000)
#define HALP_PDPT_SHIFT 30
#define HALP_PDPT_MASK 0x3FFFF
#define HALP_PDPT_SIZE (1ull << HALP_PDPT_SHIFT)

#define HALP_PD_LEVEL 2
#define HALP_PD_BASE ((HalpPageFrame *)0xFFFFFFFFC0000000)
#define HALP_PD_SHIFT 21
#define HALP_PD_MASK 0x7FFFFFF
#define HALP_PD_SIZE (1ull << HALP_PD_SHIFT)

#define HALP_PT_LEVEL 3
#define HALP_PT_BASE ((HalpPageFrame *)0xFFFFFF8000000000)
#define HALP_PT_SHIFT 12
#define HALP_PT_MASK 0xFFFFFFFFF
#define HALP_PT_SIZE (1ull << HALP_PT_SHIFT)

#endif /* _KERNEL_DETAIL_AMD64_HALPDEFS_H_ */
