# SPDX-FileCopyrightText: (C) 2025 ilmmatias
# SPDX-License-Identifier: GPL-3.0-or-later

# Status codes for KdEstabilishConnection.
KD_STATUS_TIMEOUT = -1
KD_STATUS_SUCCESS = 0
KD_STATUS_FAILURE = 1

# Definitions related to our custom debugger protocol.
KDP_DEBUG_PACKET_CONNECT_REQ = 0x00
KDP_DEBUG_PACKET_PRINT = 0x01
KDP_DEBUG_PACKET_BREAK = 0x02
KDP_DEBUG_PACKET_READ_PHYSICAL_REQ = 0x03
KDP_DEBUG_PACKET_READ_VIRTUAL_REQ = 0x04
KDP_DEBUG_PACKET_READ_PORT_REQ = 0x05
KDP_DEBUG_PACKET_READ_REGISTERS_REQ = 0x06

# ACKs always have the higher (7th) bit set.
KDP_DEBUG_PACKET_CONNECT_ACK = 0x80
KDP_DEBUG_PACKET_READ_PHYSICAL_ACK = 0x83
KDP_DEBUG_PACKET_READ_VIRTUAL_ACK = 0x84
KDP_DEBUG_PACKET_READ_PORT_ACK = 0x85
KDP_DEBUG_PACKET_READ_REGISTERS_ACK = 0x86

# Format for the custom debugger protocol structure.
KDP_DEBUG_PACKET_FORMAT = "<B"
KDP_DEBUG_PACKET_READ_ADDRESS_FORMAT = "<BQBLL"
KDP_DEBUG_PACKET_READ_PORT_REQ_FORMAT = "<BQB"
KDP_DEBUG_PACKET_READ_PORT_ACK_FORMAT = "<BQBL"

# Definitions related to the current state/context.
KDP_STATE_NONE = 0
KDP_STATE_READ_PHYSICAL = 1
KDP_STATE_READ_VIRTUAL = 2
KDP_STATE_READ_PORT = 3

# Internal context.
KdpCurrentState = KDP_STATE_NONE
