name: amd64 (Release)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  LLVM_VERSION: 22

jobs:
  build:
    runs-on: ubuntu-26.04

    steps:
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          clang-${{ env.LLVM_VERSION }} \
          cmake \
          genisoimage \
          libclang-${{ env.LLVM_VERSION }}-dev \
          lld \
          lld-${{ env.LLVM_VERSION }} \
          llvm-${{ env.LLVM_VERSION }} \
          mtools \
          ninja-build

    - name: Checkout llvm-project
      uses: actions/checkout@v4
      with:
        repository: llvm/llvm-project
        ref: release/${{ env.LLVM_VERSION }}.x
        path: llvm-project

    - name: Checkout palladium
      uses: actions/checkout@v4
      with:
        path: palladium

    - name: Build and install compiler-rt
      run: |
        PALLADIUM_PATH=${{github.workspace}}/palladium \
        COMPILER_RT_PATH=${{github.workspace}}/llvm-project/compiler-rt \
        COMPILER_RT_TARGET=x86_64 \
        LLVM_SUFFIX=-${{ env.LLVM_VERSION }} \
        palladium/tools/build-compiler-rt.sh

    - name: Configure palladium
      run: |
        cmake \
          -S palladium/src \
          -B build.target \
          -G Ninja \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
          -DARCH=amd64 \
          -DLLVM_SUFFIX=-${{ env.LLVM_VERSION }}

    - name: Build palladium
      run: cmake --build build.target --config ${{env.BUILD_TYPE}}

    - name: Build images
      run: |
        palladium/tools/build-image.sh \
          --build-dir build.target \
          --output-dir build.images

    - name: Upload images
      uses: actions/upload-artifact@v4
      with:
        name: palladium-amd64-release
        path: |
          build.images/fat.img
          build.images/iso9660.iso
        if-no-files-found: error
