name: amd64 BIOS (Release)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install packages
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository -y "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy main"
        sudo apt install -y build-essential cmake ninja-build clang lld llvm libclang-dev mkisofs

    - name: Checkout llvm-project
      uses: actions/checkout@v3
      with:
        repository: llvm/llvm-project
        ref: release/16.x
        path: llvm-project

    - name: Checkout JWasm
      uses: actions/checkout@v3
      with:
        repository: Baron-von-Riedesel/JWasm
        path: JWasm

    - name: Checkout palladium
      uses: actions/checkout@v3
      with:
        path: palladium

    - name: Configure compiler-rt for Boot
      run: |
        cmake \
          -S llvm-project/compiler-rt \
          -B llvm-project/build.boot \
          -G Ninja \
          -DCMAKE_AR=/usr/bin/llvm-ar \
          -DCMAKE_ASM_COMPILER_TARGET="i686-w64-mingw32" \
          -DCMAKE_ASM_FLAGS="-I${{github.workspace}}/palladium/src/sdk/crt/include"   \
          -DCMAKE_C_COMPILER=/usr/bin/clang \
          -DCMAKE_C_COMPILER_WORKS=true \
          -DCMAKE_C_COMPILER_TARGET="i686-w64-mingw32" \
          -DCMAKE_C_FLAGS="-I${{github.workspace}}/palladium/src/sdk/crt/include -ffreestanding" \
          -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld" \
          -DCMAKE_NM=/usr/bin/llvm-nm \
          -DCMAKE_RANLIB=/usr/bin/llvm-ranlib \
          -DCOMPILER_RT_OS_DIR="baremetal" \
          -DCOMPILER_RT_BAREMETAL_BUILD=ON \
          -DCOMPILER_RT_BUILD_BUILTINS=ON \
          -DCOMPILER_RT_BUILD_CRT=OFF \
          -DCOMPILER_RT_BUILD_LIBFUZZER=OFF \
          -DCOMPILER_RT_BUILD_MEMPROF=OFF \
          -DCOMPILER_RT_BUILD_PROFILE=OFF \
          -DCOMPILER_RT_BUILD_SANITIZERS=OFF \
          -DCOMPILER_RT_BUILD_XRAY=OFF \
          -DCOMPILER_RT_DEFAULT_TARGET_ONLY=ON \
          -DLLVM_CONFIG_PATH=/usr/bin/llvm-config

    - name: Build compiler-rt for Boot
      run: cmake --build llvm-project/build.boot

    - name: Install compiler-rt for Boot
      run: sudo cmake --build llvm-project/build.boot --target install

    - name: Configure compiler-rt for Target
      run: |
        cmake \
          -S llvm-project/compiler-rt \
          -B llvm-project/build.target \
          -G Ninja \
          -DCMAKE_AR=/usr/bin/llvm-ar \
          -DCMAKE_ASM_COMPILER_TARGET="x86_64-w64-mingw32" \
          -DCMAKE_ASM_FLAGS="-I${{github.workspace}}/palladium/src/sdk/crt/include"   \
          -DCMAKE_C_COMPILER=/usr/bin/clang \
          -DCMAKE_C_COMPILER_WORKS=true \
          -DCMAKE_C_COMPILER_TARGET="x86_64-w64-mingw32" \
          -DCMAKE_C_FLAGS="-I${{github.workspace}}/palladium/src/sdk/crt/include -ffreestanding" \
          -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld" \
          -DCMAKE_NM=/usr/bin/llvm-nm \
          -DCMAKE_RANLIB=/usr/bin/llvm-ranlib \
          -DCOMPILER_RT_OS_DIR="baremetal" \
          -DCOMPILER_RT_BAREMETAL_BUILD=ON \
          -DCOMPILER_RT_BUILD_BUILTINS=ON \
          -DCOMPILER_RT_BUILD_CRT=OFF \
          -DCOMPILER_RT_BUILD_LIBFUZZER=OFF \
          -DCOMPILER_RT_BUILD_MEMPROF=OFF \
          -DCOMPILER_RT_BUILD_PROFILE=OFF \
          -DCOMPILER_RT_BUILD_SANITIZERS=OFF \
          -DCOMPILER_RT_BUILD_XRAY=OFF \
          -DCOMPILER_RT_DEFAULT_TARGET_ONLY=ON \
          -DLLVM_CONFIG_PATH=/usr/bin/llvm-config

    - name: Build compiler-rt for Target
      run: cmake --build llvm-project/build.target

    - name: Install compiler-rt for Target
      run: sudo cmake --build llvm-project/build.target --target install

    - name: Build JWasm
      run: make -C JWasm -f GccUnix.mak

    - name: Install JWasm
      run: sudo cp JWasm/build/GccUnixR/jwasm /usr/local/bin

    - name: Configure Host Tools
      run: cmake -S palladium/src/sdk/host -B palladium/build.host -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build Host Tools
      run: cmake --build palladium/build.host --config ${{env.BUILD_TYPE}}

    - name: Configure Boot
      run: cmake -S palladium/src -B palladium/build.boot -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DARCH=x86

    - name: Build Boot
      run: cmake --build palladium/build.boot --config ${{env.BUILD_TYPE}}

    - name: Configure Target
      run: cmake -S palladium/src -B palladium/build.target -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DARCH=amd64

    - name: Build Target
      run: cmake --build palladium/build.target --config ${{env.BUILD_TYPE}}

    - name: Create system root
      run: |
        mkdir -p _root/Boot
        mkdir -p _root/System

        cat <<EOF >_root/Boot/bootmgr.ini
        DefaultSelection=BootInstall
        Timeout=5

        [BootInstall]
        Type=palladium
        Text=Boot from the Installation Disk
        Icon=boot()/Boot/install.bmp
        SystemFolder=boot()/System
        Drivers=[
            acpi.sys
            pci.sys
        ]

        [Test]
        Type=chainload
        Text=Boot from the First Hard Disk
        Icon=boot()/Boot/os.bmp
        Path=bios(80)
        EOF

        cp icons/* _root/Boot/
        cp palladium/build.boot/boot/bootsect/iso9660boot.com _root/iso9660boot.com
        cat palladium/build.boot/boot/startup/startup.com palladium/build.boot/boot/bootmgr/bootmgr.exe > _root/bootmgr
        cp palladium/build.target/kernel/kernel.exe _root/System/kernel.exe
        cp palladium/build.target/drivers/acpi/acpi.sys _root/System/acpi.sys
        cp palladium/build.target/drivers/pci/pci.sys _root/System/pci.sys

    - name: Build boot image
      run: mkisofs -iso-level 2 -R -b iso9660boot.com -no-emul-boot -o palladium/build.target/iso9660.iso _root

    - uses: actions/upload-artifact@v3
      with:
        name: iso9660.iso
        path: palladium/build.target/iso9660.iso
